FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY frontend/ .

EXPOSE 3000

# Run only the frontend (vite) part
CMD ["npm", "run", "frontend"]